# Generated by Django 4.1.3 on 2022-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='pImages')),
                ('ldt', models.DateTimeField(default=False)),
                ('lstatus', models.CharField(choices=[('AtTime', 'AtTime'), ('Early', 'Early'), ('OverTime', 'OverTime')], default=False, max_length=50)),
            ],
        ),
    ]
