# Generated by Django 4.1.3 on 2022-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('fpid', models.IntegerField(unique=True)),
                ('joiningdatetime', models.DateTimeField()),
            ],
        ),
    ]
