# Generated by Django 4.1.3 on 2022-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fingerprintprofilemodel_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkintime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.TimeField(default=None),
        ),
    ]
