# Generated by Django 4.1.3 on 2022-11-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fingerprintprofilemodel_checkinstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
