# Generated by Django 4.1.3 on 2022-11-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fingerprintprofilemodel_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
