# Generated by Django 4.1.3 on 2022-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fingerprintprofilemodel_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkintime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.CharField(max_length=100),
        ),
    ]
