# Generated by Django 4.1.3 on 2022-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_fingerprintprofilemodel_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
