# Generated by Django 4.1.3 on 2022-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_fingerprintprofilemodel_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkintime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='currentdate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='exitstatus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='fpid',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
