# Generated by Django 4.1.3 on 2022-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_fingerprintprofilemodel_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='fpid',
            field=models.IntegerField(default=0),
        ),
    ]
