# Generated by Django 4.1.3 on 2022-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_fingerprintprofilemodel_fpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='checkouttime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fingerprintprofilemodel',
            name='currentdate',
            field=models.DateField(),
        ),
    ]
